### ISSUE TITLE
[Bug] Items that don't seem to be obtainable and other small things

### ISSUE THREAD

**Issue by Vapaman** [warjort/GTCE-Inventory#1]
**Is your feature request related to a problem? Please describe.**
The item Storage Interface and Keep in Stock items don's seem to be obtainable. If there is a way to obtain them, it should be documented in the JEI. Also cables and generators don't seem to connect to the inventory pipes, so the only way to power the system is through solar or battery buffers.

**Describe the solution you'd like**
A way to obtain these items, or a better documentation. Also the cables should connect to the pipes as described in the documentation.

Picture of the cable problem
![kuva](https://user-images.githubusercontent.com/77460466/139322069-efbfb93f-7a83-43dd-9b41-8d473a846575.png)

**Comment by warjort** [comment]
Summary of your issue:
* Recipes - this looks to be a breakage in base GTCE
* Energy connections - this is a visual glitch

More details:
The first part of your problem looks to have been caused by this change:
https://github.com/GregTechCE/GregTech/pull/1634

Although it claims to be backwards compatible, it actually removes support for recipes using json files.
This is the mechanism GTCE-Inventory uses for its default recipes of these covers.
https://github.com/warjort/GTCE-Inventory/tree/main/src/main/resources/assets/gtceinventory/recipes

https://github.com/GregTechCE/GregTech/pull/1634 removed this configuration file:
https://github.com/GregTechCE/GregTech/pull/1634/files#diff-6bd7d0de42d2dce889814e6cb857a3880d82150771d5ad201ddca88c8990246f
This was probably a mistake, i.e. it looks like a recipe when it is actually a configuration file for recipe factories.

You should be able to recreate the default recipes with crafttweaker they are basically shapeless recipes:
conveyor + inventory pipe -> interface module
interface module + chip -> stock module
repeated for each energy tier

On the connection issue with cables and generators that is just a visual glitch.

The way GTCE pipes/cables work is that it checks the pipe type when drawing connections.
Since inventory pipes and energy cables are different types it won't draw them as connected.

But they are still connected. If you install TheOneProbe (TOP), you can see the inventory pipes are getting power.

Fixes:
* For the default recipes, I will change this mod to not use now broken json configuration mechanism.
* For the pipe/cable visual glitch, that would need a change to the way base GTCE draws its energy cables (its not something I can fix in this mod).

**Comment by warjort** [comment]
> GregTechCE/GregTech#1634 removed this configuration file:

I haven't tried this, but you might be able to fix it yourself by re-adding the configuration file:

assets/gregtech/recipes/_factories.json
````
{
  "ingredients": {
    "metaitem": "gregtech.common.crafting.MetaItemIngredientFactory"
  },
  "recipes": {
    "metaitem_shapeless": "gregtech.common.crafting.MetaItemShapelessRecipeFactory",
	  "metaitem_shaped": "gregtech.common.crafting.MetaItemShapedRecipeFactory"
  }
}
````
Your would need something like the resource loader mod that lets you create an ad hoc resource pack from a directory.

The factory classes mentioned in that configuration file still exist in the GTCE codebase.

**Comment by warjort** [comment]
> Your would need something like the resource loader mod that lets you create an hoc resource pack from a directory.

Or it might even work with the vanilla mechanism for adding resource packs?

**Comment by Vapaman** [comment]
Thanks for a quick response! Also can confirm that the cables are indeed connected.
